    # .github/workflows/deploy-to-cloud-run.yml

    name: CI/CD to Render (Flask App)

    on:
      push:
        branches:
          - main # Trigger on pushes to the main branch

    jobs:
      build-test-deploy:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Set up Python
            uses: actions/setup-python@v5
            with:
              python-version: '3.11'

          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
              pip install playwright # Install Playwright for E2E tests
              playwright install     # Install browser binaries
            working-directory: ./d_pipeline

          - name: Run Unit Tests (Pytest)
            run: |
              # Create a simple test file for demonstration
              echo "
              import pytest
              from app import app

              @pytest.fixture
              def client():
                  app.config['TESTING'] = True
                  with app.test_client() as client:
                      yield client

              def test_hello_world(client):
                  response = client.get('/')
                  assert response.status_code == 200
                  assert b'Hello, World!' in response.data

              def test_health_check(client):
                  response = client.get('/healthz')
                  assert response.status_code == 200
                  assert b'healthy' in response.data
              " > test_app.py
              pytest
            working-directory: ./d_pipeline

          - name: Run E2E Tests (Playwright) - Requires deployed app URL
            # This step will initially fail until you get the Render URL.
            # We'll need to update this with the actual deployed URL later.
            # For now, we'll use a placeholder or skip it if it's too complex.
            # Better to run E2E after deployment.
            # Let's move this to a separate job or make it dependent on a successful deploy.
            # For this initial setup, we'll keep it simple and focus on the deployment.
            # We can add E2E as a post-deployment check later.
            run: |
              # Placeholder for Playwright E2E test.
              # This would typically run *after* deployment to the actual URL.
              # For now, we'll just ensure Playwright installs correctly.
              echo "Playwright installed. E2E tests will be added after deployment."
            working-directory: ./d_pipeline

          - name: Trigger Render Deployment
            # This step sends a POST request to Render's deploy hook
            run: |
              curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
            env:
              # Store your Render Deploy Hook URL as a GitHub Secret
              RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
