    # .github/workflows/deploy-to-cloud-run.yml

    name: CI/CD to Google Cloud Run (Flask App)

    on:
      push:
        branches:
          - main # Trigger on pushes to the main branch

    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      REGION: ${{ secrets.GCP_REGION }}
      SERVICE_NAME: hello-world-flask
      ARTIFACT_REGISTRY_REPO: hello-world-repo

    jobs:
      build-and-deploy:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Set up Python
            uses: actions/setup-python@v5
            with:
              python-version: '3.11'

          - name: Install dependencies
            # Run pip install from the d_pipeline directory
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
            working-directory: ./d_pipeline # <<< ADD THIS LINE

          - name: Run Unit Tests # Using pytest
            # Run pytest from the d_pipeline directory
            run: |
              # The test_app.py created here will be in the correct context
              echo "
              import pytest
              from app import app

              @pytest.fixture
              def client():
                  app.config['TESTING'] = True
                  with app.test_client() as client:
                      yield client

              def test_hello_world(client):
                  response = client.get('/')
                  assert response.status_code == 200
                  assert b'Hello, World!' in response.data

              def test_health_check(client):
                  response = client.get('/healthz')
                  assert response.status_code == 200
                  assert b'healthy' in response.data
              " > test_app.py
              pip install pytest
              pytest
            working-directory: ./d_pipeline # <<< ADD THIS LINE

          - name: Authenticate to Google Cloud
            id: 'auth'
            uses: 'google-github-actions/auth@v2'
            with:
              credentials_json: '${{ secrets.GCP_SA_KEY }}'

          - name: Set up Cloud SDK
            uses: 'google-github-actions/setup-gcloud@v2'

          - name: Configure Docker to use Artifact Registry
            run: gcloud auth configure-docker ${REGION}-docker.pkg.dev

          - name: Build and Push Docker image to Artifact Registry
            # Build Docker image from the d_pipeline directory
            run: |
              gcloud artifacts repositories describe ${ARTIFACT_REGISTRY_REPO} --location=${REGION} --project=${PROJECT_ID} || \
              gcloud artifacts repositories create ${ARTIFACT_REGISTRY_REPO} --repository-format=docker --location=${REGION} --project=${PROJECT_ID} --description="Docker repository for Flask app"

              IMAGE_NAME=${REGION}-docker.pkg.dev/${PROJECT_ID}/${ARTIFACT_REGISTRY_REPO}/${SERVICE_NAME}:${GITHUB_SHA}

              # The build context '.' will now refer to ./d_pipeline
              docker build -t ${IMAGE_NAME} .
              docker push ${IMAGE_NAME}
            working-directory: ./d_pipeline # <<< ADD THIS LINE

          - name: Deploy to Cloud Run
            id: deploy
            uses: google-github-actions/deploy-cloudrun@v2
            with:
              service: ${{ env.SERVICE_NAME }}
              region: ${{ env.REGION }}
              image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY_REPO }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
              flags: --allow-unauthenticated
