# .github/workflows/deploy-to-cloud-run.yml

name: CI/CD to Render (Flask App)

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

# Environment variables available to all jobs in this workflow
env:
  RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
  APP_URL: ${{ secrets.RENDER_APP_URL }}
  JIRA_ISSUE_KEY: 'SCRUM-8' # IMPORTANT: Replace with your actual Jira Issue Key (e.g., 'DP-1', 'FLASK-123')
                               # You can find this on your Jira story card/page.

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install playwright
          playwright install
        working-directory: ./d_pipeline

      - name: Run Unit Tests (Pytest)
        run: |
            pytest
          working-directory: ./d_pipeline

      - name: Trigger Render Deployment
        run: |
          curl -X POST ${{ env.RENDER_DEPLOY_HOOK_URL }}

      - name: Wait for Render deployment to be live (Optional but recommended for E2E)
        run: |
          echo "Waiting for Render deployment to become live..."
          sleep 30

      - name: Run E2E Tests (Playwright)
        run: |
          pytest playwright_test.py
        working-directory: ./d_pipeline
        env:
          APP_URL: ${{ env.APP_URL }}

      # --- NEW STEP FOR JIRA UPDATE ---
      - name: Jira Login
        if: success()
        uses: atlassian/gajira-login@v3.0.0 # Using Atlassian's official login action
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Update Jira Issue Status on Successful Deployment
        if: success() # Only run this step if all previous steps passed
        uses: atlassian/gajira-transition@v3.0.0 # Using Atlassian's official transition action
        with:
          issue: ${{ env.JIRA_ISSUE_KEY }}
          transition: 'Done' # Or the exact name/ID of your "Done" or "Deployed" status
                            # You might need to find the exact transition ID or name in your Jira workflow.
                            # Common names: 'Done', 'Deployed', 'Closed'.

